#!/bin/sh

set -x
set -e

. debian/tests/util

username="smbtest$$"
password="$$"
add_user "${username}" "${password}"

myshare="myshare$$"
add_share "${myshare}"

echo "Creating file with random data and computing its md5"
populate_share "${myshare}" "${username}"

rm -f downloaded-data
echo "Downloading file and comparing its md5"
smbclient //localhost/"${myshare}" -U "${username}"%"${password}" -c "get data downloaded-data"

mv -f downloaded-data data
md5sum -c data.md5
