#!/bin/sh

set -x
set -e

. debian/tests/util

username="smbtest$$"
password="$$"

add_user "${username}" "${password}"

echo "Testing with incorrect password: must fail"
smbclient -L localhost -U "${username}"%wrongpass && exit 1

echo "Testing with correct password: must work"
smbclient -L localhost -U "${username}"%"${password}"

