#!/usr/bin/dh-exec --with-scripts=filter-build-profiles
# when there are any real changes in the publically visible libs (usr/lib/*/libfoo.so.N*),
# especially the soname changes, check for pkgs which depend on samba-libs (eg sssd-ad)
# and add Breaks for packages/versions using old libs to d/control
# Here, always specify libs with soname (libfoo.so.1*, not libfoo.so.*)
# Not all of the below public libraries are actually public
usr/lib/*/libdcerpc-binding.so.0*
usr/lib/*/libdcerpc-samr.so.0*
usr/lib/*/libdcerpc-server-core.so.0*
usr/lib/*/libdcerpc-server.so.0*
usr/lib/*/libdcerpc.so.0*
usr/lib/*/libndr-krb5pac.so.0*
usr/lib/*/libndr-nbt.so.0*
usr/lib/*/libndr-standard.so.0*
usr/lib/*/libndr.so.4*
usr/lib/*/libnetapi.so.1*
usr/lib/*/libsamba-credentials.so.1*
usr/lib/*/libsamba-errors.so.1*
usr/lib/*/libsamba-hostconfig.so.0*
usr/lib/*/libsamba-passdb.so.0*
usr/lib/*/libsamba-util.so.0*
usr/lib/*/libsamdb.so.0*
usr/lib/*/libsmbconf.so.0*
usr/lib/*/libsmbldap.so.2*
usr/lib/*/libtevent-util.so.0*
# heimdal libraries (used by samba and winbind)
<!pkg.samba.mitkrb5> usr/lib/*/samba/libasn1-private-samba.so.0
<!pkg.samba.mitkrb5> usr/lib/*/samba/libcom-err-private-samba.so.0
<!pkg.samba.mitkrb5> usr/lib/*/samba/libgssapi-private-samba.so.0
<!pkg.samba.mitkrb5> usr/lib/*/samba/libhcrypto-private-samba.so.0
<!pkg.samba.mitkrb5> usr/lib/*/samba/libheimbase-private-samba.so.0
<!pkg.samba.mitkrb5> usr/lib/*/samba/libheimntlm-private-samba.so.0
<!pkg.samba.mitkrb5> usr/lib/*/samba/libhx509-private-samba.so.0
<!pkg.samba.mitkrb5> usr/lib/*/samba/libkrb5-private-samba.so.0
<!pkg.samba.mitkrb5> usr/lib/*/samba/libroken-private-samba.so.0
<!pkg.samba.mitkrb5> usr/lib/*/samba/libwind-private-samba.so.0
#
usr/lib/*/samba/auth/
usr/lib/*/samba/bind9/dlz_bind9_*.so
usr/lib/*/samba/gensec/*.so
usr/lib/*/samba/libCHARSET3-private-samba.so.0
usr/lib/*/samba/libLIBWBCLIENT-OLD-private-samba.so.0
usr/lib/*/samba/libMESSAGING-SEND-private-samba.so.0
usr/lib/*/samba/libMESSAGING-private-samba.so.0
usr/lib/*/samba/libREG-FULL-private-samba.so.0
usr/lib/*/samba/libRPC-SERVER-LOOP-private-samba.so.0
usr/lib/*/samba/libad-claims-private-samba.so.0
usr/lib/*/samba/libaddns-private-samba.so.0
usr/lib/*/samba/libads-private-samba.so.0
usr/lib/*/samba/libasn1util-private-samba.so.0
usr/lib/*/samba/libauth-unix-token-private-samba.so.0
usr/lib/*/samba/libauth-private-samba.so.0
usr/lib/*/samba/libauth4-private-samba.so.0
usr/lib/*/samba/libauthkrb5-private-samba.so.0
usr/lib/*/samba/libauthn-policy-util-private-samba.so.0
usr/lib/*/samba/libcli-cldap-private-samba.so.0
usr/lib/*/samba/libcli-ldap-common-private-samba.so.0
usr/lib/*/samba/libcli-ldap-private-samba.so.0
usr/lib/*/samba/libcli-nbt-private-samba.so.0
usr/lib/*/samba/libcli-smb-common-private-samba.so.0
usr/lib/*/samba/libcli-spoolss-private-samba.so.0
usr/lib/*/samba/libcliauth-private-samba.so.0
usr/lib/*/samba/libclidns-private-samba.so.0
usr/lib/*/samba/libcluster-private-samba.so.0
usr/lib/*/samba/libcmdline-contexts-private-samba.so.0
usr/lib/*/samba/libcmdline-private-samba.so.0
usr/lib/*/samba/libcommon-auth-private-samba.so.0
usr/lib/*/samba/libdb-glue-private-samba.so.0
usr/lib/*/samba/libdbwrap-private-samba.so.0
usr/lib/*/samba/libdcerpc-pkt-auth-private-samba.so.0
usr/lib/*/samba/libdcerpc-samba-private-samba.so.0
usr/lib/*/samba/libdcerpc-samba4-private-samba.so.0
usr/lib/*/samba/libdnsserver-common-private-samba.so.0
usr/lib/*/samba/libdsdb-garbage-collect-tombstones-private-samba.so.0
usr/lib/*/samba/libdsdb-module-private-samba.so.0
usr/lib/*/samba/libevents-private-samba.so.0
usr/lib/*/samba/libflag-mapping-private-samba.so.0
usr/lib/*/samba/libgenrand-private-samba.so.0
usr/lib/*/samba/libgensec-private-samba.so.0
usr/lib/*/samba/libgpext-private-samba.so.0
usr/lib/*/samba/libgpo-private-samba.so.0
usr/lib/*/samba/libgse-private-samba.so.0
usr/lib/*/samba/libhttp-private-samba.so.0
usr/lib/*/samba/libinterfaces-private-samba.so.0
usr/lib/*/samba/libiov-buf-private-samba.so.0
usr/lib/*/samba/libkrb5samba-private-samba.so.0
usr/lib/*/samba/libldbsamba-private-samba.so.0
usr/lib/*/samba/liblibcli-lsa3-private-samba.so.0
usr/lib/*/samba/liblibcli-netlogon3-private-samba.so.0
usr/lib/*/samba/liblibsmb-private-samba.so.0
usr/lib/*/samba/libmessages-dgm-private-samba.so.0
usr/lib/*/samba/libmessages-util-private-samba.so.0
usr/lib/*/samba/libmsghdr-private-samba.so.0
usr/lib/*/samba/libmsrpc3-private-samba.so.0
usr/lib/*/samba/libndr-samba-private-samba.so.0
usr/lib/*/samba/libndr-samba4-private-samba.so.0
usr/lib/*/samba/libnetif-private-samba.so.0
usr/lib/*/samba/libnpa-tstream-private-samba.so.0
usr/lib/*/samba/libpac-private-samba.so.0
usr/lib/*/samba/libposix-eadb-private-samba.so.0
usr/lib/*/samba/libprinting-migrate-private-samba.so.0
usr/lib/*/samba/libprocess-model-private-samba.so.0
usr/lib/*/samba/libregistry-private-samba.so.0
usr/lib/*/samba/libreplace-private-samba.so.0
usr/lib/*/samba/libsamba-cluster-support-private-samba.so.0
usr/lib/*/samba/libsamba-debug-private-samba.so.0
usr/lib/*/samba/libsamba-modules-private-samba.so.0
usr/lib/*/samba/libsamba-security-private-samba.so.0
usr/lib/*/samba/libsamba-sockets-private-samba.so.0
usr/lib/*/samba/libsamba3-util-private-samba.so.0
usr/lib/*/samba/libsamdb-common-private-samba.so.0
usr/lib/*/samba/libsocket-blocking-private-samba.so.0
usr/lib/*/samba/libscavenge-dns-records-private-samba.so.0
usr/lib/*/samba/libstable-sort-private-samba.so.0
usr/lib/*/samba/libsys-rw-private-samba.so.0
usr/lib/*/samba/libsecrets3-private-samba.so.0
usr/lib/*/samba/libserver-id-db-private-samba.so.0
usr/lib/*/samba/libserver-role-private-samba.so.0
usr/lib/*/samba/libservice-private-samba.so.0
usr/lib/*/samba/libsmb-transport-private-samba.so.0
usr/lib/*/samba/libsmbclient-raw-private-samba.so.0
usr/lib/*/samba/libsmbd-base-private-samba.so.0
usr/lib/*/samba/libsmbd-shim-private-samba.so.0
usr/lib/*/samba/libsmbldaphelper-private-samba.so.0
usr/lib/*/samba/libsmbpasswdparser-private-samba.so.0
usr/lib/*/samba/libtalloc-report-printf-private-samba.so.0
usr/lib/*/samba/libtdb-wrap-private-samba.so.0
usr/lib/*/samba/libtime-basic-private-samba.so.0
usr/lib/*/samba/libtrusts-util-private-samba.so.0
usr/lib/*/samba/libutil-reg-private-samba.so.0
usr/lib/*/samba/libutil-setid-private-samba.so.0
usr/lib/*/samba/libutil-tdb-private-samba.so.0
usr/lib/*/samba/libxattr-tdb-private-samba.so.0
usr/lib/*/samba/process_model/*.so
